### ISSUE TITLE
pretorched

### ISSUE THREAD

**Issue by printf0776** [tub-cv-group/conclugen#1]
不好意思，请问defaults.yaml和to_edit.yaml在哪里呀

**Comment by florianblume** [comment]
Hi, `defaults.yaml` was missing, I uploaded it now, thanks for pointing that out. `to_edit.yaml` is a config you have to create where you define what you want to run. None of the people on our project speak Chinese (but English, German, Arabic), please make the effort to translate your question next time so everyone can understand it, thanks!

PS: An editable config could look like this:

```yaml
trainer:
  min_epochs: 50
  max_epochs: 1000

model:
  init_args:
    batch_size: 4096
    representation_dim: 4096
    img_size: [180, 180]
    num_classification_head_layers: 1
    num_attention_heads: null
    finetune_layers:
      classifier: all
    losses: ['class']
    model_weights_path: [insert path from pertaining here]
    optimizer_init:
      class_path: torch.optim.AdamW
      init_args:
        lr: 0.00967
        weight_decay: 0.00004
    lr_scheduler_init:
      class_path: torch.optim.lr_scheduler.SequentialLR
      init_args:
        milestones: [5]
      schedulers: 
      - class_path: torch.optim.lr_scheduler.LinearLR
        init_args:
          start_factor: 0.1
          total_iters: 5
      - class_path: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
        init_args:
          T_0: 20
          T_mult: 2
          eta_min: 0.000001

data:
  init_args:
    num_cpus: 14
    cache_features: cpu

fit:
  ckpt_path: null
validate:
  ckpt_path: null
test:
  ckpt_path: best

cometml_workspace: self-supervised-fer
exp_name: [your-experiment-name]
machine: [your machine name]
```
